---
version: "3.8"

services:
  biru:
    container_name: biru
    image: ghcr.io/vheuel/biru:main
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      BIRU_CONFIG: "ewogICAgImRvbWFpbnMiOiB7CiAgICAgICAgImJza3kubWFrZXVwIjogewogICAgICAgICAgICAicHJvdmlkZXIiOiAiYnNreV9tYWtldXAiLAogICAgICAgICAgICAiem9uZUlkIjogIjUwZjE0NDNkNTA4MDYxMDdkNjliNDhlZDRkZTNjYmQyIiwKICAgICAgICAgICAgImRpc2FsbG93ZWRTdWJkb21haW5zIjogWwogICAgICAgICAgICAgICAgInZoZXVlbCIKICAgICAgICAgICAgXQogICAgICAgIH0sCiAgICAgICAgImJza3kudG9kYXkiOiB7CiAgICAgICAgICAgICJwcm92aWRlciI6ICJic2t5X3RvZGF5IiwKICAgICAgICAgICAgInpvbmVJZCI6ICJiNjJlOTJmYmVkYmEwMjE1ZWQ0MTQ1ZjNiZjcyOTg4NyIsCiAgICAgICAgICAgICJkaXNhbGxvd2VkU3ViZG9tYWlucyI6IFsKICAgICAgICAgICAgICAgICJ2aGV1ZWwiCiAgICAgICAgICAgIF0KICAgICAgICB9LAogICAgICAgICJza2VldHMudG9wIjogewogICAgICAgICAgICAicHJvdmlkZXIiOiAic2tlZXRzX3RvcCIsCiAgICAgICAgICAgICJ6b25lSWQiOiAiMDZmMDY0MmU1OTI0MmY4MjBkMTYyMzFlMmRhYjliNmIiLAogICAgICAgICAgICAiZGlzYWxsb3dlZFN1YmRvbWFpbnMiOiBbCiAgICAgICAgICAgICAgICAidmhldWVsIgogICAgICAgICAgICBdCiAgICAgICAgfQogICAgfSwKICAgICJwcm92aWRlcnMiOiB7CiAgICAgICAgImJza3lfbWFrZXVwIjogewogICAgICAgICAgICAic2VydmljZSI6ICJjbG91ZGZsYXJlIiwKICAgICAgICAgICAgInRva2VuIjogIm4xQVZIZmhXUFRld0xZV1NfVlpTR0JTRTdGOGRtQXUzeGVQTGlSdW0iLAogICAgICAgICAgICAiYXR0ZXN0YXRpb24iOiB7CiAgICAgICAgICAgICAgICAidmVyaWZpZWQiOiB0cnVlCiAgICAgICAgICAgIH0KICAgICAgICB9LAogICAgICAgICJic2t5X3RvZGF5IjogewogICAgICAgICAgICAic2VydmljZSI6ICJjbG91ZGZsYXJlIiwKICAgICAgICAgICAgInRva2VuIjogIldVUGRDeVVzWEZkYUI3a1p5NjQ2WkFPa0ptQ0NIMUFvdUl3eFNpZHYiLAogICAgICAgICAgICAiYXR0ZXN0YXRpb24iOiB7CiAgICAgICAgICAgICAgICAidmVyaWZpZWQiOiB0cnVlCiAgICAgICAgICAgIH0KICAgICAgICB9LAogICAgICAgICJza2VldHNfdG9wIjogewogICAgICAgICAgICAic2VydmljZSI6ICJjbG91ZGZsYXJlIiwKICAgICAgICAgICAgInRva2VuIjogIjN6Q1gtTXZpSXBXNTdpZkxqTDl3UzJiazFrZ3g2dlMyYllzVzgxczIiLAogICAgICAgICAgICAiYXR0ZXN0YXRpb24iOiB7CiAgICAgICAgICAgICAgICAidmVyaWZpZWQiOiB0cnVlCiAgICAgICAgICAgIH0KICAgICAgICB9CiAgICB9Cn0K"
      POSTGRES_URL: "postgres://default:o91NjHJrPizU@ep-round-sun-a1h210od-pooler.ap-southeast-1.aws.neon.tech:5432/verceldb?sslmode=require"
      # TG_BOT_TOKEN: ""
      # TG_CHAT_ID: ""
    depends_on:
      - biru-postgres
    networks:
      - biru
  biru-postgres:
    container_name: biru-postgres
    image: postgres
    restart: unless-stopped
    volumes:
      - "/your/data/dir:/var/lib/postgresql/data:rw"
    environment:
      POSTGRES_DB: "verceldb"
      POSTGRES_USER: "default"
      POSTGRES_PASSWORD: "o91NjHJrPizU"
    networks:
      - biru
networks:
  biru:
